spring:
  application:
    name: assignment
  cloud:
    gcp:
      project-id: local-assignment-project
      pubsub:
        emulator-host: localhost:8085

app:
  pubsub:
    output-topic: orders.transformed
    failed-topic: orders.failed
    retry:
      max-attempts: 3
      backoff-ms: 1000

logging:
  level:
    com.pubsub.assignment: DEBUG
    org.springframework.web: INFO
  structured:
    format:
      console: ecs