spring.application.name=assignment
spring.cloud.gcp.project-id=local-assignment-project
spring.cloud.gcp.pubsub.emulator-host=localhost:8085
app.pubsub.output-topic=orders.transformed
logging.level.com.pubsub.assignment=DEBUG
logging.level.org.springframework.web=INFO
logging.structured.format.console=ecs